title: GitHub Copilot CLI for Beginners
description: A comprehensive beginner-friendly course teaching you how to use GitHub Copilot CLI to accelerate your development workflow
theme: jekyll-theme-cayman
show_downloads: true
github:
  repository_url: https://github.com/SenukDias/copilot-cli-training-basic
  zip_url: https://github.com/SenukDias/copilot-cli-training-basic/zipball/master
  tar_url: https://github.com/SenukDias/copilot-cli-training-basic/tarball/master

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
